require('mihir-k.plugins_config.mason')
require('mihir-k.plugins_config.lsp')
require('mihir-k.plugins_config.treesitter')
require('mihir-k.plugins_config.format-on-save')
require('mihir-k.plugins_config.lualine')
